from Song import Song

song_key = {
    'https://www.youtube.com/watch?v=gr4cqcqnAN0': Song('State of Grace', False),
    'https://www.youtube.com/watch?v=fnI07MzNWzA': Song('Red', False),
    'https://www.youtube.com/watch?v=OE2RVmaioAo': Song('Treacherous', False),
    'https://www.youtube.com/watch?v=2RukVfByHVM': Song('I Knew You Were Trouble', False),
    'https://www.youtube.com/watch?v=aPnqx56V8-0': Song('All Too Well', False),
    'https://www.youtube.com/watch?v=xGWTv4IQ7vQ': Song('22', False),
    'https://www.youtube.com/watch?v=VzggqDYcuVg': Song('I Almost Do', False),
    'https://www.youtube.com/watch?v=DA5IFd2TFjQ': Song('We Are Never Ever Getting Back Together', False),
    'https://www.youtube.com/watch?v=QEYTzDJO_eM': Song('Stay Stay Stay', False),
    'https://www.youtube.com/watch?v=CQ8L-PaDfyc': Song('The Last Time', False),
    'https://www.youtube.com/watch?v=NA90OVe2ixo': Song('Holy Ground', False),
    'https://www.youtube.com/watch?v=iKTSubwwq8Y': Song('Sad Beautiful Tragic', False),
    'https://www.youtube.com/watch?v=MOc2VuNqAQc': Song('The Lucky One', False),
    'https://www.youtube.com/watch?v=SWQwtE9N5aU': Song('Everything Has Changed', False),
    'https://www.youtube.com/watch?v=90JHxH7bVaQ': Song('Starlight', False),
    'https://www.youtube.com/watch?v=bVcxtHhyfZQ': Song('Begin Again', False),
    'https://www.youtube.com/watch?v=dcNG2Ua0YSs': Song('Ronan', False),
    'https://www.youtube.com/watch?v=wyWI1vA8WX4': Song('The Moment I Knew', False),
    'https://www.youtube.com/watch?v=0y7FnmhZuaw': Song('Come Back... Be Here', False),
    'https://www.youtube.com/watch?v=Nbnuq6r90kg': Song('Girl At Home', False),
    'https://www.youtube.com/watch?v=VwCQAP-XPA8': Song('Better Man', False),
    'https://www.youtube.com/watch?v=EsiqARpjOBQ': Song('Nothing New', False),
    'https://www.youtube.com/watch?v=3XGlNU__M68': Song('Babe', False),
    'https://www.youtube.com/watch?v=fFMPxt-XNIk': Song('Message In A Bottle', False),
    'https://www.youtube.com/watch?v=Aifi_CiXDeM': Song('I Bet You Think About Me', False),
    'https://www.youtube.com/watch?v=UVa0YRSbK9E': Song('Forever Winter', False),
    'https://www.youtube.com/watch?v=b7Qse2cuHmg': Song('Run', False),
    'https://www.youtube.com/watch?v=kwYXepzkhWY': Song('The Very First Night', False)
}